// <auto-generated />
using System;
using EscuelaPrimariaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EscuelaPrimariaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260102172319_Correcion de relaciones innecesarias")]
    partial class Correcionderelacionesinnecesarias
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApoderadoEstudiante", b =>
                {
                    b.Property<int>("ApoderadosidApoderado")
                        .HasColumnType("int");

                    b.Property<int>("menoresACargoidEstudiante")
                        .HasColumnType("int");

                    b.HasKey("ApoderadosidApoderado", "menoresACargoidEstudiante");

                    b.HasIndex("menoresACargoidEstudiante");

                    b.ToTable("ApoderadoEstudiante");
                });

            modelBuilder.Entity("EscuelaPrimariaAPI.Models.Apoderado", b =>
                {
                    b.Property<int>("idApoderado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idApoderado"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTelf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idApoderado");

                    b.ToTable("Apoderados");
                });

            modelBuilder.Entity("EscuelaPrimariaAPI.Models.Estudiante", b =>
                {
                    b.Property<int>("idEstudiante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idEstudiante"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Discapacidad")
                        .HasColumnType("bit");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Repitente")
                        .HasColumnType("bit");

                    b.Property<int?>("idProfesor")
                        .HasColumnType("int");

                    b.Property<int?>("idSeccion")
                        .HasColumnType("int");

                    b.Property<string>("imgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idEstudiante");

                    b.HasIndex("idProfesor");

                    b.HasIndex("idSeccion");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("EscuelaPrimariaAPI.Models.Profesor", b =>
                {
                    b.Property<int>("idProfesor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idProfesor"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idProfesor");

                    b.ToTable("Profesores");
                });

            modelBuilder.Entity("EscuelaPrimariaAPI.Models.Seccion", b =>
                {
                    b.Property<int>("idSeccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idSeccion"));

                    b.Property<int>("Grado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("idProfesor")
                        .HasColumnType("int");

                    b.Property<int?>("idTurno")
                        .HasColumnType("int");

                    b.HasKey("idSeccion");

                    b.HasIndex("idProfesor");

                    b.HasIndex("idTurno");

                    b.ToTable("Secciones");
                });

            modelBuilder.Entity("EscuelaPrimariaAPI.Models.Turno", b =>
                {
                    b.Property<int>("idTurno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTurno"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idTurno");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("ApoderadoEstudiante", b =>
                {
                    b.HasOne("EscuelaPrimariaAPI.Models.Apoderado", null)
                        .WithMany()
                        .HasForeignKey("ApoderadosidApoderado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EscuelaPrimariaAPI.Models.Estudiante", null)
                        .WithMany()
                        .HasForeignKey("menoresACargoidEstudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EscuelaPrimariaAPI.Models.Estudiante", b =>
                {
                    b.HasOne("EscuelaPrimariaAPI.Models.Profesor", "Docente")
                        .WithMany()
                        .HasForeignKey("idProfesor");

                    b.HasOne("EscuelaPrimariaAPI.Models.Seccion", "Seccion")
                        .WithMany("Estudiantes")
                        .HasForeignKey("idSeccion");

                    b.Navigation("Docente");

                    b.Navigation("Seccion");
                });

            modelBuilder.Entity("EscuelaPrimariaAPI.Models.Seccion", b =>
                {
                    b.HasOne("EscuelaPrimariaAPI.Models.Profesor", "Profesor")
                        .WithMany()
                        .HasForeignKey("idProfesor");

                    b.HasOne("EscuelaPrimariaAPI.Models.Turno", "Turno")
                        .WithMany()
                        .HasForeignKey("idTurno");

                    b.Navigation("Profesor");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("EscuelaPrimariaAPI.Models.Seccion", b =>
                {
                    b.Navigation("Estudiantes");
                });
#pragma warning restore 612, 618
        }
    }
}
